# Professional Telegram YouTube Downloader Bot - Railway Configuration

[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production.variables]
LOG_LEVEL = "INFO"
MAX_CONCURRENT_DOWNLOADS = "5"
RATE_LIMIT_REQUESTS = "30"
RATE_LIMIT_PERIOD = "60"
ENABLE_ANALYTICS = "true"
ENABLE_SECURITY = "true"
PYTHONUNBUFFERED = "1"
PYTHONDONTWRITEBYTECODE = "1"